# HERE IT'S OUR BASE REPOSITORY. REMEMBER: WHEN YOU FELL
# CONFORTABLE WITH THE MVC WITH SEVERAL MODELS, TRY TO ADD
# AN INHERITANCE WAY TO NOT REPETAT YOUR CODE. FOR EXAMPLE:
# ALL OF THEM ARE SHARING THE ADD,LIST,DELETE,MODIFY METHODS.
require "csv"
class Repository
  def initialize(csv_file)

  end
  def add
  end

  def list
  end

end
